forhomework0
KhelychEl/itc-front pull request #1
Opened 2018-03-16 14:22 UTC by KhelychEl

2018-03-18 08:26 UTC, mlshv requested changes
частые ошибки не читаем, а зря

2018-03-18 08:26 UTC, mlshv commented on Howework 0/HW0.js
> +	///Main2///
чёт многовато пустых строк между функциями. 1-2 достаточно

2018-03-18 08:26 UTC, mlshv commented on Howework 0/HW0.js
> +		return number1+number2;
лучше ставить пробелы между операндами и оператором

2018-03-18 08:26 UTC, mlshv commented on Howework 0/HW0.js
> +			mergeArray[i] = array1[i];
грязная функция.

функция должна что-то получать, работать с этим и что-то возвращать.

она не должна знать о чём-то кроме своих аргументов. и она не должна их изменять - только читать.

2018-03-18 08:26 UTC, mlshv commented on Howework 0/HW0.js
> +		return mergeArray;
вообще, лучше погугли как это делается.

(спойлер - в одну строчку)

2018-03-18 08:26 UTC, mlshv commented on Howework 0/HW0.js
> +				console.log(arrayPeople[i]);
и ещё. зачем ты юзаешь табы? используй пробелы. поставь форматтер в редактор и не парься. спроси в чат как это сделать

2018-03-18 08:26 UTC, mlshv commented on Howework 0/HW0.js
> +			result += arguments[i];
читай.
частые.
ошибки.

2018-03-18 08:26 UTC, mlshv commented on Howework 0/HW0.js
> +		newQueryArray.push(key);
где вложенность?

2018-03-20 16:15 UTC, mlshv requested changes
приведи код в порядок. внимательно прочитай частые ошибки про консистенси и кодстайл. у тебя последнее ревью

2018-03-20 16:15 UTC, mlshv commented on Howework 0/HW0.js
> +let array2 = [4,5];
зачем эти двое? в чате помогут

2018-03-20 16:15 UTC, mlshv commented on Howework 0/HW0.js
> +    let result = argumentsArray.reduce(function (previousValue, currentValue) {
зачем let?

2018-03-20 16:15 UTC, mlshv commented on Howework 0/HW0.js
> +function ChoosePeople (people) {
почему с большой буквы?

почему function? где консистенси?

2018-03-22 09:26 UTC, KhelychEl commented
Изменил выявленные тобой ошибки. Прочитал про кодстайл и консистенси. Везде объявляю функции только через function, следовал всем советам кодстайла из learnjavascript.

2018-03-26 08:10 UTC, mlshv approved these changes

2018-03-26 08:10 UTC, merged